const prompt = require('prompt-sync')()
nota1 = prompt("Insira a primeira nota ")
nota2 = prompt("Insira a segunda nota ")
nota3 = prompt("Insira a terceira nota ")
nota4 = prompt("Insira a quarta nota ")
nota5 = prompt("Insira a quinta nota ")
nota6 = prompt("Insira a sexta nota ")
nota7 = prompt("Insira a sétima nota ")
nota8 = prompt("Insira a oitava nota ")
nota9 = prompt("Insira a nona nota ")
nota10 = prompt("Insira a décima nota ")
console.log({nota1})
console.log({nota2})
console.log({nota3})
console.log({nota4})
console.log({nota5})
console.log({nota6})
console.log({nota7})
console.log({nota8})
console.log({nota9})
console.log({nota10})
lista = new Array(nota1.concat(",",nota2, ",", nota3, ",", nota4, ",", nota5, ",", nota6, ",", nota7, ",", nota8, ",", nota9, ",", nota10))
console.log(lista)
notas = new Array(10)
notas.unshift(nota3)
notas.unshift(nota4)
notas.unshift(nota5)
console.log(notas)
for(index in notas) {
    console.log(index, notas[index])
}
list = new Array
list.unshift("4")
console.log(list)
list.unshift("1")
console.log(list)
list.push("2")
console.log(list)
list.push("5")
console.log(list)
list.push("9")
console.log(list)
console.log(list.pop())
console.log(list)
console.log(list.shift())
console.log(list)
numeros = [10, 20, 30]
for (i = 0; i < numeros.length; i++) {
    console.log(numeros[i])
}
soma = (numeros[0])+(numeros[1])+(numeros[2])
console.log(soma)
media = (soma)/3
console.log(media)